# state_operations.py - Auto-generated state variable helpers
# Location: src/aimfp/.state/state_operations.py
# Generated by AIMFP during project initialization
#
# Standalone by design: this file must NOT import from the aimfp package. It is a
# drop-in state layer, and the package it sits beside is the very thing that
# generates it. `.state/` is excluded from the wheel (setuptools skips dot-prefixed
# directories), so nothing here ships.
#
# AIMFP itself has no mutable global state to replace — this exists so the
# FP-compliant alternative is already in place if that ever changes.

from typing import Final, Optional, Any
from dataclasses import dataclass
import sqlite3
import json
import os

# Read-only constant for database path
STATE_DB_PATH: Final[str] = os.path.join(os.path.dirname(__file__), "runtime.db")


@dataclass(frozen=True)
class Result:
    """Result type for explicit error handling."""
    success: bool
    data: Optional[Any] = None
    error: Optional[str] = None


# === Core Variable Operations ===

def set_var(var_name: str, value: Any, var_type: Optional[str] = None) -> Result:
    """
    Effect: Store variable in state database.

    Replaces mutable global variables with database-backed state.

    Args:
        var_name: Variable identifier (e.g., 'counter', 'config_debug_mode')
        value: Value to store (will be JSON-serialized)
        var_type: Optional type hint ('int', 'str', 'bool', 'dict', 'list')

    Returns:
        Result with success status
    """
    conn = sqlite3.connect(STATE_DB_PATH)
    try:
        # Serialize value
        if isinstance(value, (dict, list)):
            serialized_value = json.dumps(value)
            inferred_type = 'dict' if isinstance(value, dict) else 'list'
        elif isinstance(value, bool):
            serialized_value = json.dumps(value)
            inferred_type = 'bool'
        elif isinstance(value, (int, float)):
            serialized_value = str(value)
            inferred_type = 'int' if isinstance(value, int) else 'float'
        else:
            serialized_value = str(value)
            inferred_type = 'str'

        conn.execute(
            """INSERT OR REPLACE INTO variables (var_name, var_value, var_type, updated_at)
               VALUES (?, ?, ?, CURRENT_TIMESTAMP)""",
            (var_name, serialized_value, var_type or inferred_type)
        )
        conn.commit()
        return Result(success=True)
    except Exception as e:
        return Result(success=False, error=f"Failed to set variable: {str(e)}")
    finally:
        conn.close()


def get_var(var_name: str) -> Result:
    """
    Effect: Retrieve variable from state database.

    Args:
        var_name: Variable identifier

    Returns:
        Result with deserialized value or error
    """
    conn = sqlite3.connect(STATE_DB_PATH)
    try:
        row = conn.execute(
            "SELECT var_value, var_type FROM variables WHERE var_name=?",
            (var_name,)
        ).fetchone()

        if not row:
            return Result(success=False, error=f"Variable '{var_name}' not found")

        value_str, var_type = row[0], row[1]

        # Deserialize based on type
        if var_type == 'int':
            value = int(value_str)
        elif var_type == 'float':
            value = float(value_str)
        elif var_type in ('bool', 'dict', 'list'):
            value = json.loads(value_str)
        else:
            value = value_str

        return Result(success=True, data=value)
    except Exception as e:
        return Result(success=False, error=f"Failed to get variable: {str(e)}")
    finally:
        conn.close()


def delete_var(var_name: str) -> Result:
    """
    Effect: Delete variable from state database.

    Args:
        var_name: Variable identifier

    Returns:
        Result with success status
    """
    conn = sqlite3.connect(STATE_DB_PATH)
    try:
        conn.execute("DELETE FROM variables WHERE var_name=?", (var_name,))
        conn.commit()

        if conn.total_changes == 0:
            return Result(success=False, error=f"Variable '{var_name}' not found")

        return Result(success=True)
    except Exception as e:
        return Result(success=False, error=f"Failed to delete variable: {str(e)}")
    finally:
        conn.close()


def increment_var(var_name: str, amount: int = 1) -> Result:
    """
    Effect: Increment numeric variable (creates if doesn't exist).

    Common use case for counters.

    Args:
        var_name: Variable identifier
        amount: Amount to increment by (default 1)

    Returns:
        Result with new value
    """
    result = get_var(var_name)

    if not result.success:
        # Create new counter starting at 0
        current_value = 0
    else:
        current_value = result.data
        if not isinstance(current_value, (int, float)):
            return Result(success=False, error=f"Variable '{var_name}' is not numeric")

    new_value = current_value + amount
    set_result = set_var(var_name, new_value, 'int')

    if not set_result.success:
        return set_result

    return Result(success=True, data=new_value)


def list_vars(var_type: Optional[str] = None) -> Result:
    """
    Effect: List all variables (optionally filtered by type).

    Args:
        var_type: Optional type filter ('int', 'str', 'bool', etc.)

    Returns:
        Result with list of variable names
    """
    conn = sqlite3.connect(STATE_DB_PATH)
    try:
        if var_type:
            rows = conn.execute(
                "SELECT var_name FROM variables WHERE var_type=? ORDER BY var_name",
                (var_type,)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT var_name FROM variables ORDER BY var_name"
            ).fetchall()

        var_names = [row[0] for row in rows]
        return Result(success=True, data=var_names)
    except Exception as e:
        return Result(success=False, error=f"Failed to list variables: {str(e)}")
    finally:
        conn.close()
